# Generated by Django 5.0.2 on 2024-02-19 18:25

import django.db.models.deletion
from django.db import migrations, models
import json
from django.contrib.contenttypes.models import ContentType
from location.models import Country, City


def load_data(apps, schema_editor):
    with open('../../fixtures/countries.json') as f:
        countries = json.load(f)
        for country_data in countries:
            Country.objects.create(
                name=country_data['name'],
                search_text=country_data['search_text'],
                search_count=country_data['search_count'],
                code=country_data['code'],
                phone_code=country_data['phone_code']
            )

    with open('../../fixtures/cities.json') as f:
        cities = json.load(f)
        for city_data in cities:
            country = Country.objects.get(name=city_data['country'])
            City.objects.create(
                name=city_data['name'],
                search_text=city_data['search_text'],
                search_count=city_data['search_count'],
                country=country
            )




class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('search_text', models.CharField(max_length=100)),
                ('search_count', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=3)),
                ('phone_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('search_text', models.CharField(max_length=100)),
                ('search_count', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('search_text', models.CharField(max_length=100)),
                ('search_count', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=3)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='location.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='location.country')),
            ],
        ),
        migrations.RunPython(load_data),
    ]
